### ISSUE TITLE
Third party dependencies in Release folder is not included in the installer

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#101]
I'm considering integrating Shimmer into an existing application which currently uses wyUpdate. This application has many thirdparty dependencies such as cefsharp and multiple sub directories (which needs to be copied recursively). You could say the Release folder is final output from which the application is packaged from (installer, updates, yadayada). 

So basically i need a way to specify a list of thirdparty libraries and folders to include with the installer when creating a new release. 

**Just to clarify**: Everything the application needs to run is already present in the Release directory, so a relative path to each dependency (whether it be a dynamic library or a directory) would be sufficient.

**Comment by anaisbetts** [comment]
Yep, you can totally do this, you need to put it in your nuspec under the `<files>` section, you can create arbitrarily complicated folder structures from there, even if your Release folder is just a flat list of files.

**Comment by peters** [comment]
@paulcbetts Thanks! ;)
