### ISSUE TITLE
c++ redistributable as a prerequisite

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#103]
It is mentioned in the wiki that specifying prerequisites during installation is not supported at the moment. But when it is, it should be possible to specify a c++ runtime to install if it's not present on the user's computer.

**Comment by anaisbetts** [comment]
@peters We don't need this, but if you do, you should open a PR with your idea for a solution. Though to be honest, I'd just package the version of the CRT you want along with the rest of the binaries, as long as you're using VS2010 or higher, the CRT is "just a DLL", you don't have to "install" it like the old days.

**Comment by peters** [comment]
Yes, i agree. Packaging the correct CRT would be sufficient, but does Shimmer have the ability to include thirdparty dll's ? See https://github.com/github/Shimmer/issues/101
