### ISSUE TITLE
Expose a -ReleasesDirectory option on New-Release

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#106]
> Also, is it possible to specify a custom path to the 'Releases' directory? I would like to use an UNC path where are releases are stored (per application) so i do not have to worry about keeping a backup on my local developer machine.

**Comment by allenpetersen** [comment]
Create-Release.ps1, or whatever script we should use on build servers, will also need this. All of our builds are archived on separate system. Using a UNC path for this share location would be ideal.

**Comment by shiftkey** [comment]
@allenpetersen once I merge in #111 then the changes will be available to both inside and outside Visual Studio
