### ISSUE TITLE
Subfolders not respected

### ISSUE THREAD

**Issue by allenpetersen** [Squirrel/OldSquirrelForWindows#108]
We require installing some files into a subfolder under our main install path. 

UpdateManager.installPackageToAppDir() currently will find all of the files but it will create all of the files in the single install folder.

If your NuGet package as the following files.

```
lib/net40/app.exe
lib/net40/sub/another.file
```

Your install folder will look like this

```
app-1.0.0/app.exe
app-1.0.0/another.file
```

I've made a change here that address the initial install and adding a file with a subsequent diff package. But it I didn't test removing a file in a subfolder.

https://github.com/allenpetersen/Shimmer/commit/7e09546237c592f25302c3d96d6cdc02d848e860

**Comment by shiftkey** [comment]
This change is included in version `0.6.19-beta`
