### ISSUE TITLE
BuildPackage is not respected

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#123]
per application configuration. I only want to produce nupkg packages when 'Release', 'ReleaseRemote', 'ReleaseTestUpdate' are selected, but if 'RemoteDebugging', 'ReleaseRemoteDebugging' are selected i'm not interested in a Shimmer build. 

I tried moving BuildPackage into the 'Release' configuration on the main project but still all configuration produces a nupkg.

I also tried to build a couple of projects who are not referenced by the main project. Such as 'pkg.remote.tests, pkg.remote.update.tests, pkg.remote.update.release.tests' but then suddenly nuget pack fails, but that's understandable... but it should never have attempted to build a nupkg in the first place.

I tried adding `<BuildPackage>false</BuildPackage>` to each project, but it still attempts to create a nupkg. 

This is a major showstopper! :(

**Comment by shiftkey** [comment]
On install, the `BuildPackage` element is inserted into the first PropertyGroup:

``` xml
  <PropertyGroup>
   <!-- bunch of other elements -->
   <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">.\</SolutionDir>
   <RestorePackages>true</RestorePackages>
   <BuildPackage>True</BuildPackage>
  </PropertyGroup>
```

If you set that that to `false` that will stop the package creation.

The creating of the packages is done by the NuGet integration with VS, not Shimmer, so I'd need a bit more about what the `csproj` file looks like to diagnose what might be happening here.

**Comment by peters** [comment]
Great, i'll email you tonight.

**Comment by peters** [comment]
@shiftkey You got mail.

**Comment by peters** [comment]
@shiftkey Poor research on my side. I can confirm this is working correctly, but https://github.com/github/Shimmer/issues/129 had me going for a while.
