### ISSUE TITLE
Content Files should be deployed in app directory

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#125]
> If you take a look inside the nupkg i sent you, you can see the Content directory. That directory is not extracted during installation (it's not present in the final path after a successfull installation). My program depends on all those files. If you open the nuspec, you can see those dependencies derive from <files />

To be investigated, but suspect:
- expected behaviour: `Content` files inside created Shimmer package are deployed to application directory
- actual behaviour: only `Lib` files are deployed - content is ignored

**Comment by peters** [comment]
This bug is still present in 0.6.20

**Comment by shiftkey** [comment]
@peters It's the next thing on my list :)

**Comment by peters** [comment]
:+1:

**Comment by shiftkey** [comment]
Fixed in `0.6.22`

**Comment by peters** [comment]
Great! Waiting for the nuget channels to update :/

**Comment by shiftkey** [comment]
@peters i'm waiting for my slow internets to publish it! :trollface:

**Comment by shiftkey** [comment]
Boom: https://www.nuget.org/packages/Shimmer/0.6.22

**Comment by peters** [comment]
![24914893](https://f.cloud.github.com/assets/869/1119990/f6950a42-1a8c-11e3-8820-32845f20e1d7.jpg)

**Comment by peters** [comment]
Still working on confirming that everything works :)

**Comment by peters** [comment]
As far as i can tell, the extraction process is flawless! :+1: :+1: :+1:

**Comment by peters** [comment]
Though there has to be a bug in the nuget dependency resolve graph Shimmer is using because in my release folder there are several dll's that are not included in the nupkg. Two of these dll's are actual nuget packaged, but others plain references. How should i proceed?

**Comment by shiftkey** [comment]
@peters regarding the assemblies issue - please open up a different issue and walk me through how your doing things
