### ISSUE TITLE
Do not change/overwrite BuildPackage value when Shimmer nuget package is updated

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#129]
This happens each time you update the Shimmer nuget package. Then `<BuildPackage>True</Buildpackage>` is added to the main .csproj. This should only happen if the property is not present. In my case this value is set to 'False' and it is enabled expliclity in certain build configurations.

**Comment by shiftkey** [comment]
I'd need to go back and test [this code](https://github.com/github/Shimmer/blob/master/src/CreateReleasePackage/tools/utilities.psm1#L176) to see how it was detecting "no value defined" versus "false is found".

**Comment by peters** [comment]
@shiftkey Bug still present in 0.6.25
