### ISSUE TITLE
Exclude certain dependencies from Nuget package

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#139]
If you are [repacking msil](https://github.com/gluck/il-repack) using [ILRepack.MSBuild.Task](https://github.com/peters/ILRepack.MSBuild.Task) on multiple dependencies (assembly references or whatever), i want to exclude those files from the generated nupkg. 

Why? Imagine you are merging 15 dynamic libraries into one, interalize their namespace and then merge into the main assembly and later on obsfucate the darn thing.

Security by obscurity :lollipop:

**Comment by shiftkey** [comment]
Assemblies which are not part of the main library are always opt-in. Basically [this section](https://github.com/github/Shimmer/wiki/Specifying-The-Right-Dependencies#external-libraries) is what you need to do.

If you're merging assemblies into the main assembly together you shouldn't need to include them (or exclude them).

Or am I missing something about the requirements?

**Comment by peters** [comment]
They are a part of the main assembly, but `AfterBuild`:

Merge dependencies:

A.dll
B.dll
C.dll
D.dll

into **autokollekt.infrastructure.dll** (which also is a referenced project) 

Exclude the following dependencies from .nupkg:
A, B, C, D

**Comment by shiftkey** [comment]
Creating the package occurs after the build finishes, so I don't think:
- those assemblies will be around
- you have to do anything to include/exclude them if they're included in the infrastructure.dll

**Comment by peters** [comment]
Hmm, maybe i'm doing it wrong then... because they are present in the application install directory.

**Comment by shiftkey** [comment]
Are they included in either nuspec file?

**Comment by peters** [comment]
No

**Comment by peters** [comment]
I'll whip up a sample project for you. It's not that important anyway, so don't let it block a v0.7 release

**Comment by shiftkey** [comment]
All good, I'll keep powering through in the meantime...

**Comment by peters** [comment]
:+1:

**Comment by shiftkey** [comment]
So I know NuGet 2.7 added support for **development dependencies**

> This feature was contributed by Adam Ralph and it allows package authors to declare dependencies that were only
> used at development time and don't require package dependencies. By adding a `developmentDependency="true"`
> attribute to a package in packages.config, nuget.exe pack will no longer include that package as a dependency.

I can test on our end that we're respecting these tags, but does that sound like what you need?

**Comment by shiftkey** [comment]
Confirmed with NuGet 2.7 -

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Mono.Options" version="1.1" targetFramework="net40" developmentDependency="true" />
</packages>
```

Generated nuspec file:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ProjectWithDevelopmentDependency</id>
    <version>1.0</version>
    <authors>shiftkey</authors>
    <owners>shiftkey</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Let's test that development packages are excluded</description>
    <dependencies />
  </metadata>
</package>
```

That's how I'd go about ignoring packages which have been merged into this project :boom:
