### ISSUE TITLE
Little bit of doco would be really helpful

### ISSUE THREAD

**Issue by JakeGinnivan** [Squirrel/OldSquirrelForWindows#17]
I have only spent 30 mins or so poking around, but some high level doco about how things fit together and get started would be super handy. I will leave my spiking to after there is some doco or you can quickly run me through it (on skype or something).

**Comment by haacked** [comment]
The docs are right here: [](https://github.com/github/Shimmer)

:P

**Comment by chrismcv** [comment]
agreed, this would be really useful

**Comment by kellyelton** [comment]
I second and third.

**Comment by anaisbetts** [comment]
This project has more documentation than any other project I've ever created! Go look in [the specs folder](https://github.com/github/Shimmer/tree/master/specs)

**Comment by kellyelton** [comment]
I'm sure the fellow above, like me, was searching the wiki and the root of
the repo for info. Should have checked the 'Spec' folder. Maybe making a
note of that in the readme will help out.

**Comment by JakeGinnivan** [comment]
I think the most useful thing for me at the moment would be to put in the readme that the installation point is not complete :) I was looking for how to create the installer for a while, not realising that only the update functionality is done.
