### ISSUE TITLE
Applying multiple delta packages fails the checksum

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#170]
Repro steps:
- install version 1.
- deploy version 1.1 as delta package.
- deploy version 1.2 as delta package.
- check for updates (using deltas) and 2 packages are available
- downloads pass
- apply fails with mismatch in checksum

**Comment by shiftkey** [comment]
Note: a single delta update does not fail the checksum :metal:

**Comment by shiftkey** [comment]
Appears to be an issue with `New-Release` as this works:

```
var deltaBuilder = new DeltaPackageBuilder();
deltaBuilder.CreateDeltaPackage(firstRelease, secondRelease, firstDelta);
deltaBuilder.CreateDeltaPackage(secondRelease, thirdRelease, secondDelta);
```

But this does not:

```
var deltaBuilder = new DeltaPackageBuilder();
deltaBuilder.CreateDeltaPackage(firstRelease, secondRelease, firstDelta);
deltaBuilder.CreateDeltaPackage(firstRelease, thirdRelease, secondDelta);
```

**Comment by anaisbetts** [comment]
While I don't see why it wouldn't work straight away, I definitely envisioned delta releases to only go up to the very next version

**Comment by shiftkey** [comment]
@paulcbetts that's how I'd expect it to work as well
