### ISSUE TITLE
Uninstall: Shutdown running application

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#186]
The uninstaller should send a window message to the program you are attempting to uinstall, telling it to shutdown. This would solve a couple of edge cases where you mark certain files as `DELETE_ON_REBOOT`. These are pretty niché scenarios, but you are bound to have some clients trying to uninstall / install an application (without rebooting).

This is mainly related to https://github.com/github/Shimmer/issues/181

Appearently this can be achieved rather easily with Shimmer sending a window message (hey no IPC) to the target application:

``` c++
ds.dwData = WM_USER + 50; // the "message" you want to send
cds.cbData = sizeof(MyDataForMessage50); // the size of the chunk of data
cds.lpData = lpMessage50Data; // a pointer to the chunk of data
SendMessage(hwndTarget, WM_COPYDATA, reinterpret_cast<WPARAM>(hwndSender),
            reinterpret_cast<LPARAM>(&cds));
```

See [sending-a-custom-windows-message-custom-data-marshalling](http://stackoverflow.com/questions/16307338/sending-a-custom-windows-message-custom-data-marshalling)

Then you could just override a virtual method in `AppSetup` that allows the application to perform a clean shutdown (not referring to OnUninstall).

**Comment by shiftkey** [comment]
And here I was thinking a Process.Kill would be "good enough" on uninstall :)

I'll leave this one open if someone wants to have a crack at it, but I'd love to get this in sooner rather than later.

**Comment by peters** [comment]
@shiftkey Sure, give me some pointers to where Process.Kill happens and i'll provide a PR ;)

**Comment by shiftkey** [comment]
@peters nah, let's Do It The Right Way.

As for where the code should live, I think [here](https://github.com/github/Shimmer/blob/master/src/Shimmer.Client/InstallManager.cs#L166) is a good place to start experimenting...

**Comment by shiftkey** [comment]
> Sure, give me some pointers to where Process.Kill happens and i'll provide a PR ;)

I'm not doing that at the moment, it was just a (horrible) thought...

**Comment by anaisbetts** [comment]
Hm, I actually think this should be a more explicit API than just sending a window message. First of all, you have no idea that WM_USER + 50 is free, and you also have no idea how to find the (possibly multiple) window handles to target. What if the application runs in the background and doesn't _have_ a window loop?

**Comment by anaisbetts** [comment]
Instead, I would have an API that is called on startup, and opens or creates a named pipe and parks itself on a read, then the installer can send down a "Shut it down" message that all of the open applications will receive and respond to

**Comment by peters** [comment]
@paulcbetts IPC is the most proven solution, no doubt about it. [wyupdate](https://code.google.com/p/wyupdate/source/browse/trunk/UpdateHelper/PipeServer.cs) has a simple implementation available, it does the job... but it's not as elegant as how [EasyHook](http://easyhook.codeplex.com/SourceControl/latest#branches/release-2.7/Examples/FileMonitorInterceptor/EntryPoint.cs) does it ;)

**Comment by shiftkey** [comment]
@paulcbetts @peters yep, an IPC-based solution would be the most-sane way to do it

**Comment by peters** [comment]
Closing this one because of https://github.com/Squirrel/Squirrel.Windows/pull/229.
