### ISSUE TITLE
Nuget needs install1.ps to add wix projects OR...

### ISSUE THREAD

**Issue by ghost** [Squirrel/OldSquirrelForWindows#2]
Essentially the results of @distantcam's [Managed/Wix bootstrapper](https://github.com/distantcam/WiXManagedBootstrapperExample) can look like this:

![](http://i.imgur.com/6vWZn.png)

To get to that stage requires (at a minimum) four projects - the actual app, the actual installer (wix) the bootstrapper (WPF) UI, the bootstrapper (wix3.6)
#### Install1.ps

To get that into the project, we need to install one csproj and two wixprojs (which yes, would require the toolset installed). The csproj contains the UI, and thats whats needed for customisation, then the wixprojs compile that and build the MSI then EXE.

Now, we can get around the _toolset_ being installed if the WiX binary tools are available (via nuget, whatever).
#### Self contained tool

This contains a lot more work, but could give a better experience. Given limited customisation options (image, title, etc), our tools could be a buildtask/executable/whatever, take a config file, then build based on that. That'd drop the requirement to have wix toolset installed (but still need the wix/burn/etc assemblies somewhere, but thats redistributable over nuget whereas the project types aren't), but at the expense of reducing customisation. Still, it'd be a step up from Clickonce customisation

**Comment by anaisbetts** [comment]
What if we used the NuGet manifest to determine the customization stuff?

**Comment by ghost** [comment]
That could work. Actually thats probably better, because thats post-build stuff, would have information about how/where the nuget is being deployed so the installer can be built correctly

**Comment by distantcam** [comment]
It's not quite that simple. The setup project needs to know about the app (which files to install, which project to build for reference, any upgrade requirements, etc).

A custom tool would help a lot. I'm not sure what is the best way to proceed yet.

**Comment by distantcam** [comment]
Whoops. Wrong button. :P
