### ISSUE TITLE
Real world example

### ISSUE THREAD

**Issue by DoCode** [Squirrel/OldSquirrelForWindows#20]
Can you publish an real world example for better understand the technical workflow?

**Comment by anaisbetts** [comment]
All of the user-level documentation will be written once the library is finished

**Comment by alimbada** [comment]
So with the advent of Win8, we're starting to see a lot issues with ClickOnce and are looking for an alternative. Is Shimmer ready for real world usage yet? If not, what is there left to do. I'd be interested in getting involved if it helps speed things up. :-)

**Comment by anaisbetts** [comment]
@alimbada Not finished yet, I ended up having to put more work into other projects, but I'll be getting back to it very soon!  If you wanted to contribute, one thing that Shimmer handles really badly is reporting user errors (i.e. packages that are missing needed metadata, errors in creating delta / full packages, etc) - having really solid error reporting will help a lot!
