### ISSUE TITLE
Setting up file associations

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/OldSquirrelForWindows#215]
One thing I need to do with my application is have files associated with my application so they open the application if they are double clicked on. 

Is there a way with squirrel to set these up in the same way that we can with click once? (http://msdn.microsoft.com/en-us/library/vstudio/bb892924.aspx)

Stefan

**Comment by anaisbetts** [comment]
Yes, you'd need to do that in a custom installer DLL, create a DLL that implements `IAppSetup` (there's a base class that does a lot of the work for you)

**Comment by peters** [comment]
@paulcbetts Is the project dead or postponed?

**Comment by shiftkey** [comment]
@peters it's been delayed while I've been working on other things

**Comment by peters** [comment]
:+1:
