### ISSUE TITLE
CreateReleasePackage project should be a Powershell script

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#31]
Why?

1) So that it can be run from the command line - build environments etc
2) So that it can be run inside VS - dev-friendly scenarios

Not sure if you've already had a crack at it, but I'm happy to throw a bit of time at it - should be able to reuse much of what's in Shimmer.Core and just port the rest of the C# code to a PS1

**Comment by anaisbetts** [comment]
So, CreateReleasePackage is an internal EXE for Create-Release.ps1, which is supported both inside VS as well as outside of VS (if you give it some more params). Maybe that's what you're looking for?

**Comment by shiftkey** [comment]
Basically _high-five_

Sent from my Windows Phone

**Comment by anaisbetts** [comment]
I should make this more clear, otherwise people will try to use CreateReleasePackage directly.

**Comment by shiftkey** [comment]
Clowns like me should also learn to RTFM.

Sent from my Windows Phone
