### ISSUE TITLE
Microsoft.Bcl reference breaks solution on fresh load

### ISSUE THREAD

**Issue by becdetat** [Squirrel/OldSquirrelForWindows#37]
I've only just started playing so maybe i'm missing something but on a fresh clone, SampleUpdatingApp.csproj and Shimmer.Core.csproj both import `\packages\Microsoft.Bcl.1.0.11-beta\tools\portable-net40+sl4+win8+wp71\Microsoft.Bcl.targets` as a project which doesn't exist until the packages are pulled down. Which can't happen because the projects don't load. Which don't load because... well you get the idea.

**Comment by becdetat** [comment]
Workaround:
1. open `Shimmer.Core.csproj` and `SampleUpdatingApp.csproj` and comment out `<Import Project="..\packages\Microsoft.Bcl.1.0.11-beta\tools\portable-net40+sl4+win8+wp71\Microsoft.Bcl.targets" />`
2. Reload the projects
3. open PM console and run `update-package`, there is also a failure involving reactiveui-core and reactiveui-testing that I think can be ignored
4. check that `packages\Microsoft.Bcl.1.0.11-beta\tools\portable-net40+sl4+win8+wp71\Microsoft.Bcl.targets` exists
5. uncomment the import in step 1
6. reload the solution and rebuild

More problems:
1. `System.Windows.Interactivity.dll` needs to be added to /bin
2. `src\Shimmer.Tests\WiXUi\WiXUiBootstrapperTests.cs` has `using ReactiveUI.Routing;` paul no paul what are you doing paul. Add a reference in `Shimmer.Tests` to `bin\ReactiveUI.Routing.dll` and `bin\ReactiveUI.Xaml.dll` - probably due to ReactiveUI bump to 4.3.2

Now it builds. Hope this helps somebody.

**Comment by darrelmiller** [comment]
I worked around the first issue by using Install-Package Microsoft.Bcl -Pre from the Packageing Console Window.  I didn't bother hunting for the System.Windows.Interactivity.dll to solve that problem.  Although I really like the idea of the project, there seem to be a huge number of dependencies in this project just to create an installer.  Too many moving parts scare me.

**Comment by distantcam** [comment]
Yeah, I know @xpaulbettsx is in love with ReactiveUI, but with 10 libraries + BCL references pulled in by it I think it's too much for a simple installer.

**Comment by anaisbetts** [comment]
@distantcam ReactiveUI isn't used everywhere (specifically, you don't have to add it to your app for updates)

**Comment by distantcam** [comment]
@xpaulbettsx I was talking about the installer that is made. RxUI is too much for an installer IMHO. 

You don't even need a full framework. Using either a DelegateCommand, or even just implementing ICommand when you need it, and wiring up Views with ViewModels manually is possible with something as simple as the installer.

**Comment by becdetat** [comment]
I was most excited by the specification, rather than the implementation. If you just took the spec and could implement that with any installer - I use NSIS for the WinForms LOB app that keeps me mostly employed - and work in a reference updater implementation with Action<> callbacks for example.

My NSIS scripts write to `c:\program files`. My LOB app queries a database for the current version on init, then if it is out of date it checks a file share for the new version. If it finds a new version it kills itself and runs the installer.

I would love a mechanism for polling a file share for a RELEASES file, download and silently install to %appdata%\app\version in the background, then pops up a notification to the user to restart the app. It doesn't need deltas or nuget or wix etc.

I'm not ranting against Shimmer, just wishlisting. In fact I'll give it a shot myself.

**Comment by anaisbetts** [comment]
> You don't even need a full framework. Using either a DelegateCommand, or even just implementing ICommand when you need it, and wiring up Views with ViewModels manually is possible with something as simple as the installer.

The Internet is really fast nowadays :)    I see what you're saying. Shimmer's got a way to go before it's finished, I promise.

**Comment by shiftkey** [comment]
> The Internet is really fast nowadays

_"joke about Australian internets goes here"_
