### ISSUE TITLE
Simmer nuget package?

### ISSUE THREAD

**Issue by mike-marshall** [Squirrel/OldSquirrelForWindows#38]
Many of the instructions reference installing the Shimmer nuget package first.  But a search both in the VS Package Manager and nuget.org turns up 0 results.  Is it under a different name or has it been moved?  I get the feeling I am being dense but the descriptions in the specs folder all reference installing a nuget package in your WPF application solution as step number 1

**Comment by MatthewSteeples** [comment]
You need to include pre-release packages. http://nuget.org/packages?q=Shimmer&prerelease=true&sortOrder=relevance

**Comment by mike-marshall** [comment]
Thanks!

**Comment by anaisbetts** [comment]
The packages that are live right now are solely for evaluating the API (i.e. try to implement the client side, tell me if it doesn't work with your app), Shimmer isn't finished yet!

**Comment by mike-marshall** [comment]
10-4.  Just evaluating for a potential project.  I'll post back with any issues
