### ISSUE TITLE
Create-Release,ps1 fails if there are spaces in $releaseDir

### ISSUE THREAD

**Issue by recumbent** [Squirrel/OldSquirrelForWindows#46]
Specifically here: 

```
$fullRelease = & $createReleasePackageExe -o $releaseDir -p $packageDir $pkg.FullName 
## NB: For absolutely zero reason whatsoever, $fullRelease ends up being the full path Three times
$fullRelease = $fullRelease.Split(" ")[0]
echo "Full release file at $fullRelease"
```

This causes a problem when subsequently using `$fullRelease` when invoking candle.

The reason for the path being output three times (excepting that its actually twice with a subtly different path in the middle) is that the paths for the last full release and the delta file are also being output when there's an existing RELEASES file in the releases folder.

I can see half a dozen ways to "fix" this but I'm not sure what would be appropriate

**Comment by qJake** [comment]
FYI: This code no longer appears in [Create-Release.ps1](https://github.com/github/Shimmer/blob/master/Create-Release.ps1), so this bug should be closed.
