### ISSUE TITLE
Mono.Options should not be a dependency

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#48]
This means consumers of Shimmer will have it installed, despite it being compiled into the Shimmer assembly.

Kill it with :fire:

**Comment by distantcam** [comment]
There's an option in NuGet 2.7 to mark dependencies as build only, which should fix this issue.

https://nuget.codeplex.com/workitem/1956

**Comment by shiftkey** [comment]
:sparkles: Thanks for the heads-up!

**Comment by anaisbetts** [comment]
:+1:
