### ISSUE TITLE
Shimmer commands don't work with paths with spaces

### ISSUE THREAD

**Issue by distantcam** [Squirrel/OldSquirrelForWindows#68]
I created a test app in `C:\users\cameron.macfarland\documents\visual studio 2012\Projects\ShimmerTestApp` and then tried `New-Release` which spat the dummy at the path having spaces.

Specifically the error was in [commands.psm1 line 45](https://github.com/github/Shimmer/blob/master/src/CreateReleasePackage/tools/commands.psm1#L45)

Might want to put your test app in a directory with a space in the name for testing.

**Comment by shiftkey** [comment]
Ugh, yeah, will do. Thanks for the heads up.
