### ISSUE TITLE
Shimmer Vs ClickOnce

### ISSUE THREAD

**Issue by michaelsync** [Squirrel/OldSquirrelForWindows#82]
Hello,

I found this "It's like ClickOnce but Works™" interesting. But I still love to know what you guys fix for ClickOnce. 

Thanks!

**Comment by shiftkey** [comment]
- full control over the downloading and installing of files - supporting ClickOnce issues for users is hard
- so many issues [reported that probably won't be fixed ever](https://www.google.com/search?q=clickonce+proxy+update+site%3Aconnect.microsoft.com) - we need a replacement
- installable without network access - a big request
- extensibility - run custom steps as part of the installer

**Comment by anaisbetts** [comment]
@michaelsync Check out the docs folder and the readme, it will explain everything

**Comment by michaelsync** [comment]
Thanks Paul! I will check out the docs folder.

**Comment by michaelsync** [comment]
Hi Pearl, I think, "docs" folder means "specs" https://github.com/github/Shimmer/tree/master/specs right?

**Comment by shiftkey** [comment]
Yep, that's what "Pearl" meant

**Comment by michaelsync** [comment]
:) Thanks Brendan..
