### ISSUE TITLE
External Packages Folder

### ISSUE THREAD

**Issue by luizbon** [Squirrel/OldSquirrelForWindows#87]
Using a Nuget.config outside the solution folder is not working. Basically because Create-ReleaseForProject function uses $solutionDir + "packages" and this breaks.

Using Nuget.config outside solution dir is described here: http://docs.nuget.org/docs/reference/nuget-config-file

**Comment by shiftkey** [comment]
To clarify...

If you: 
- specify a nuget.config file at the same level as the solution
- which looks like this:

``` xml
 <config>
    <!--  If value starts with "$\" then location is relative to this conf file. -->
    <add key="repositorypath" value="$\External\Packages" />
 </config>
```
- then [this parameter](https://github.com/github/Shimmer/blob/master/src/CreateReleasePackage/tools/commands.psm1#L62) should use that value, not the default

**Comment by luizbon** [comment]
Tried this, but with no luck.
I'm never worked with PowerShell, but this line seems to not check the nuget.config file. Maybe it's better to check for nuget.config file from the CreateReleasePackage project just like Nuget does and use the folder defined in there.

Sorry for bugging with this, but since I don't have experience with PowerShell I can't do better tests to send a pull request.

**Comment by shiftkey** [comment]
@luizbon that's fine. I'd prefer it to be in the Powershell script for simplicity sake (we use NuGet.Core heavily, but not NuGet.exe)

I'm trying to get a first preview out the door this week so I won't be able to get to this immediately.

As it's one of the less-common NuGet features, it's not on my critical path at this stage. If someone wants to jump on it in the meantime they're more than welcome to.

**Comment by luizbon** [comment]
Just created a pull request #92 for this issue.
