### ISSUE TITLE
$fullRelease gets a bonus semi-colon at the end which prevents light.exe from building setup.exe

### ISSUE THREAD

**Issue by darrelmiller** [Squirrel/OldSquirrelForWindows#91]
This is in 0.6.13-beta.  After doing the Split on line 70 of Create-Release.ps1 I did a $fullRelease = $fullRelease.SubString(0,$fullRelease.Length - 1) and the problem went away.  I'm sure you'll find a better way :-)

**Comment by shiftkey** [comment]
You'd think this would do the job, eh?

```
$packages = $releaseOutput.Split(";")
$fullRelease = $packages[0]
```

![](http://i.imgur.com/0U2cnck.gif)

I can throw a `.TrimEnd(";")` on there but I _really_ thought `.Split(";")` would take care of it.

Thanks for the pickup.

**Comment by darrelmiller** [comment]
Maybe it is one of those special invisible semi-colons but the line of code that I am seeing in Create-Release is

$fullRelease = $fullRelease.Split(" ")[0]

**Comment by shiftkey** [comment]
Oh, that script needs to be killed with fire. Ignore that.

The right way is to run `New-Release` from the Package Manager Console in VS.

**Comment by shiftkey** [comment]
And when I say "killed with fire" I mean "considered for [build server automation](https://github.com/github/Shimmer/issues/59)".

If you're looking for something like that, chime in with what you'd like. I'll leave this open and ensure that script isn't busted.

**Comment by darrelmiller** [comment]
My bad.  I was reading the wrong docs.  I was reading this https://github.com/github/Shimmer/blob/master/specs/Tools.md

**Comment by shiftkey** [comment]
No no, my bad for not pointing you to the QuickStart: https://github.com/github/Shimmer/wiki/QuickStart

**Comment by allenpetersen** [comment]
Our CI server runs a NAnt script which uses msbuild to compile the solution and then separate tasks that create the NuGet package and call Create-Release.p1 to build the release files.

As a temporary workaround for this issue I just modified Create-Release.ps1 to strip trailing semicolons.

**Comment by shiftkey** [comment]
> As a temporary workaround for this issue I just modified Create-Release.ps1 to strip trailing semicolons.

As people are already using this `Create-Release.ps1` script, I'll add a task here to eliminate the duplication and keep those files around - #109

**Comment by anaisbetts** [comment]
RIP my crappy Create-Release script

**Comment by shiftkey** [comment]
![](http://i.imgur.com/1Wz61.gif)

**Comment by shiftkey** [comment]
It is done:

https://github.com/github/Shimmer/commit/06c92a7a85a8b647414b7d17b3cab0dfb98d88a2#diff-2

And how you too can call `Create-Release.ps1` from outside Visual Studio:

https://github.com/github/Shimmer/blob/06c92a7a85a8b647414b7d17b3cab0dfb98d88a2/tests/Create-Release.Tests.ps1#L71
