### ISSUE TITLE
Lost installation

### ISSUE THREAD

**Issue by luizbon** [Squirrel/OldSquirrelForWindows#94]
Using the nuget package it seems to lose the cmdlets.
I need to uninstall Shimmer and install again to have access to New-Release cmdlet.

**Comment by shiftkey** [comment]
What version of NuGet do you have installed? I've been testing `2.7.40808.167`

I sometimes get the `"File cannot be loaded because the execution of scripts is disabled on this system`" error after opening a solution - and I have to restart VS to get back to work. Is it something like that?

**Comment by luizbon** [comment]
My NuGet version is 2.7.40808.167 also.

I didn't see any of this message, it just don't recognize the New-Release cmdlet anymore. This problem is occurring with the NuGet package that is online in Prereleases, is not a dev repo with latest source.

**Comment by shiftkey** [comment]
Ok, so I need a couple of things to fire up the old psychic debugger:
- What version of Shimmer are you using?
- What OS and Visual Studio version?
- What does the Package Manager console tell you when you do `New-Release`?

**Comment by luizbon** [comment]
I've just create a brand new project on a new path, so packages folder is on solution folder.
- Installed Shimmer 0.6.15-beta with NuGet.
- Run New-Release without any problems.
- Restarted VS.
- New-Release doesn't exists anymore.

This is the message I've received when try to run it again:
PM> New-Resealse -Project ShowIP.Web
New-Resealse : The term 'New-Resealse' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
- New-Resealse -Project ShowIP.Web
- ~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (New-Resealse:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

I'm running a Win 8 with VS 2012 11.60610.01 Update 3. I've Resharper 8 installed too.

**Comment by flagbug** [comment]
@luizbon 

> New-Resealse

**Comment by shiftkey** [comment]
```
PM> New-Resealse -Project ShowIP.Web
```

I think the typo here is the issue - this should be `New-Release -Project ShowIP.Web`

**Comment by luizbon** [comment]
Shame on me!! My Bad, its working, all the time it was my typo.
